[options]
admin_passwd = montaga
db_host = dpg-db4amrbbc2fs73b707s0-a
db_port = 5432
db_user = openpg
db_password = 9QyhWANdNIpXQXjaS6bMK9a4Xtmnd86G
db_name = school_g6sb
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
http_port = 10000
