[options]
admin_passwd = montaga
db_host = dpg-db4amrbbc2fs73b707s0-a
db_port = 5432
db_user = school_g6sb_user
db_password = msKjZclkphwHGhcuy0Scx3QTHCAGHqjS
db_name = school_g6sb
addons_path = /usr/lib/python3/dist-packages/odoo/addons
http_port = 10000
